apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q3i645afc-python
  janus-idp.io/tekton: q3i645afc-python
  backstage.io/kubernetes-id: q3i645afc-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q3i645afc-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
